44 import products from shopify
iTechArt-RubyLab/shopify_app pull request #16
Opened 2023-07-21 06:30 UTC by ritamma

2023-07-21 15:14 UTC, fooooxmr requested changes

2023-07-21 15:14 UTC, fooooxmr commented on app/services/import_products.rb
> +        product.create_product_option(
Should have many options and variants.

2023-07-25 15:14 UTC, fooooxmr commented on app/services/import_products.rb
> +module ImportProducts
https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial
https://4ybakut2004.medium.com/%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-service-object-%D0%B2-rails-11bd26a2efaf

2023-07-25 15:14 UTC, fooooxmr approved these changes

2023-07-26 05:33 UTC, evrusha approved these changes

2023-07-26 09:28 UTC, Ikl0 approved these changes

2023-07-26 11:56 UTC, merged