35 implement customer management
iTechArt-RubyLab/shopify_app pull request #17
Opened 2023-07-21 14:59 UTC by ShalaevPavel

Added customer controller, request to shopify app

2023-07-25 08:30 UTC, fooooxmr requested changes

2023-07-25 08:30 UTC, fooooxmr commented on Gemfile
> +
Why do you removing pry gem?

2023-07-25 08:30 UTC, fooooxmr commented on app/controllers/customers_controller.rb
> +      # Handle failure case (e.g., show an error message to the user)
We should show error message to user in this case.

2023-07-25 08:30 UTC, fooooxmr commented on app/controllers/customers_controller.rb
> +      # Handle failure case (e.g., show an error message to the user)
Show error somewhere.
When you are using GPT you need also review and update code a little bit :)

2023-07-25 08:30 UTC, fooooxmr commented on app/services/customer_creation.rb
> +def create_customer_in_shopify_app
It's a bad practice to create services like this.
Try to find another realisation of the services.
https://www.toptal.com/ruby-on-rails/rails-service-objects-tutorial
https://4ybakut2004.medium.com/%D0%BF%D0%B0%D1%82%D1%82%D0%B5%D1%80%D0%BD-service-object-%D0%B2-rails-11bd26a2efaf

2023-07-25 08:52 UTC, fooooxmr commented on app/controllers/products_controller.rb
> +
Why callbacks were removed?

2023-07-25 08:53 UTC, fooooxmr commented on app/controllers/customers_controller.rb
> +    updated_customer = update_customer_in_shopify_app(customer_id, updated_customer_data)
Did you update customer data on the our side?

2023-07-26 06:56 UTC, evrusha requested changes

2023-07-26 06:56 UTC, evrusha commented on app/services/customer_creation.rb
> +require 'net/http'
For shopify requests, it's easier to use the shopify_api gem.

2023-07-28 15:08 UTC, fooooxmr commented on Gemfile.lock
> +>>>>>>> 8116b6ab5b4c1039a6dea8f1a3107c1e01fbfaf4
Fix it.

2023-07-28 15:10 UTC, fooooxmr commented on app/controllers/shopify_api_controller.rb
> +class ShopifyApiController < ApplicationController
AuthorizedController

2023-07-28 15:10 UTC, fooooxmr commented on app/models/adress.rb
> +=======
Resolve conflicts.

2023-07-28 15:10 UTC, fooooxmr commented on app/models/adress.rb
> +=======
upper variant.

2023-08-01 15:06 UTC, fooooxmr approved these changes

2023-08-01 15:07 UTC, Ikl0 approved these changes

2023-08-03 15:04 UTC, merged