5 create a customer model
iTechArt-RubyLab/shopify_app pull request #6
Opened 2023-07-13 11:45 UTC by ShalaevPavel

Added migrations and model classes
Run rails db:migrate

2023-07-13 15:27 UTC, Ikl0 requested changes

2023-07-13 15:27 UTC, Ikl0 commented on app/models/adress.rb
> +
associations are not implemented yet? or they are not needed in this models?

2023-07-13 15:27 UTC, Ikl0 commented on db/migrate/20230713112745_create_customers.rb
> +      t.string :email
I think you forgot about shopify_id(customer id from shopify)

2023-07-13 15:27 UTC, Ikl0 commented on db/migrate/20230713112750_create_addresses.rb
> +      t.integer :customer_id
same as customer(shopify_id)

2023-07-13 15:29 UTC, Ikl0 commented
Need to understand where models require if from shopify

2023-07-13 18:01 UTC, fooooxmr requested changes

2023-07-13 18:01 UTC, fooooxmr commented on db/migrate/20230713112745_create_customers.rb
> +      t.string :password_confirmation
I do not think, that we will store password in our Database.

2023-07-14 19:17 UTC, Ikl0 approved these changes

2023-07-17 15:12 UTC, fooooxmr approved these changes

2023-07-17 15:15 UTC, merged